# Development Kustomize version using right namespace.
# If using namePrefix then we need to update references.
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloudkit-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cloudkit-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: dev-cloudkit-sa
---
apiVersion: v1
kind: Secret
metadata:
  name: cluster-fulfillment-ig
type: Opaque
stringData:
  credentials: |
    # Setup here the credentials required for cluster fulfillment playbooks (AWS, OpenStack, ...)

