apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: cloudkit-aap-development

resources:
- ../../../base/cloudkit-aap


# Development naming convention
#namePrefix: dev-

# Development environment annotations
commonAnnotations:
  environment: development

labels:
- includeSelectors: true
  pairs:
    environment: development
    app.kubernetes.io/managed-by: kustomize

patches:
- patch: |-
    - op: replace
      path: /stringData/vars.yaml
      value: |-
        ---
        aap_hostname: 
        aap_username: "{{ lookup('env', 'AAP_USERNAME') }}"
        aap_password: "{{ lookup('env', 'AAP_PASSWORD') }}"
        aap_organization_name: ...
        aap_project_name: ...
        aap_project_git_uri: ...
        aap_project_git_branch: ...
        aap_ee_image: ...
        aap_validate_certs: ...
        license_manifest_path: "{{ lookup('env', 'LICENSE_MANIFEST_PATH') }}"
  target:
    kind: Secret
    name: config-as-code-ig
- patch: |-
    - op: replace
      path: /data/license.zip
      value: ""
  target:
    kind: Secret
    name: config-as-code-ig
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/image
      value: quay.io/rh-ee-jkary/cloudkit-aap-ee:latest
  target:
    kind: Job
    name: aap-bootstrap
- path: fix-ansibleautomationplatform.yaml
  target:
    kind: AnsibleAutomationPlatform
    name: dev-cloudkit
