apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: config-as-code-manifest-ig
spec:
  dataFrom:
  - extract:
      conversionStrategy: Default
      decodingStrategy: Base64
      key: nerc/hypershift2/innabox/aap-license
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: nerc-cluster-secrets
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: config-as-code-manifest-ig
