apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: default-cluster-credentials
spec:
  dataFrom:
  - extract:
      conversionStrategy: Default
      decodingStrategy: None
      key: nerc/hypershift2/innabox/default-cluster-credentials
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: nerc-cluster-secrets
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: default-cluster-credentials
