apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: quay-pull-secret
spec:
  dataFrom:
  - extract:
      conversionStrategy: Default
      decodingStrategy: None
      key: nerc/hypershift2/innabox/quay-pull-secret
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: nerc-cluster-secrets
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: quay-pull-secret
    template:
      type: kubernetes.io/dockerconfigjson
